.TH FDUPES 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
fdupes \- finds duplicate files in a given set of directories
.SH SYNOPSIS
.B fdupes
[
.I options
]
.I DIRECTORY
\|.\|.\|.

.SH "DESCRIPTION"
Searches the given path for duplicate files. Such files are found by
comparing file sizes and MD5 signatures, followed by a 
byte-by-byte comparison.

.SH OPTIONS
.TP
.B -r --recurse
include files residing in subdirectories
.TP
.B -s --symlinks
follow symlinked directories
.TP
.B -H --hardlinks
normally, when two or more files point to the same disk area they are
treated as non-duplicates; this option will change this behavior
.TP
.B -n --noempty
exclude zero-length files from consideration
.TP
.B -f --omitfirst
omit the first file in each set of matches
.TP
.B -1 --sameline
list each set of matches on a single line
.TP
.B -S --size
show size of duplicate files
.TP
.B -q --quiet
hide progress indicator
.TP
.B -d --delete
prompt user for files to preserve, deleting all others (see
.B CAVEATS
below)
.TP
.B -v --version
display fdupes version
.TP
.B -h --help
displays help
.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR md5sum (1)
.SH NOTES
Unless
.B -1
or
.B --sameline
is specified, duplicate files are listed
together in groups, each file displayed on a separate line. The
groups are then separated from each other by blank lines.

When
.B -1
or
.B --sameline
is specified, spaces and backslash characters  (\fB\e\fP) appearing
in a filename are preceded by a backslash character.
.SH CAVEATS
If fdupes returns with an error message such as
.B fdupes: error invoking md5sum
it means the program has been compiled to use an external
program to calculate MD5 signatures (otherwise, fdupes uses
interal routines for this purpose), and an error has occurred
while attempting to execute it. If this is the case, the 
specified program should be properly installed prior 
to running fdupes.

When using
.B \-d
or
.BR \-\-delete ,
care should be taken to insure against
accidental data loss.

When used together with options
.B \-s
or
.BR \-\-symlink ,
a user could accidentally
preserve a symlink while deleting the file it points to.

Furthermore, when specifying a particular directory more than
once, all files within that directory will be listed as their
own duplicates, leading to data loss should a user preserve a
file without its "duplicate" (the file itself!).

.SH AUTHOR
Adrian Lopez <adrian2@caribe.net>

